# This is a simple Travis config for a project that only needs to install pure
# Python dependencies. For more complex setups, you can use conda on Travis:
# http://conda.pydata.org/docs/travis.html

language: python
python:
  - "3.5"
  - "3.6"
  - "3.4"
  - "2.7"
# Install any dependencies for running the tests:
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov pytest-cov
# command to run tests
script: py.test tests --cov=differential_privacy
after_success:
  codecov